Trigger

diff --git a/.github/workflows/circleci-trigger.yml b/.github/workflows/circleci-trigger.yml
--- a/.github/workflows/circleci-trigger.yml
+++ b/.github/workflows/circleci-trigger.yml
@@ -1,73 +1,73 @@
-name: Trigger CircleCI Pipeline
+# name: Trigger CircleCI Pipeline
 
-on:
-  push:
-    branches:
-      - dev
-      - main
+# on:
+#   push:
+#     branches:
+#       - dev
+#       - main
 
-  workflow_dispatch:
-    inputs:
-      branch:
-        description: "Branch to trigger"
-        required: true
-        default: dev
-        type: choice
-        options:
-          - dev
-          - main
+#   workflow_dispatch:
+#     inputs:
+#       branch:
+#         description: "Branch to trigger"
+#         required: true
+#         default: dev
+#         type: choice
+#         options:
+#           - dev
+#           - main
 
-jobs:
-  trigger-circleci:
-    runs-on: ubuntu-latest
+# jobs:
+#   trigger-circleci:
+#     runs-on: ubuntu-latest
 
-    defaults:
-      run:
-        shell: bash
+#     defaults:
+#       run:
+#         shell: bash
 
-    steps:
-      - name : Setup runtime variables
-        id : setup
-        run: |
-          BRANCH="${{ inputs.branch || github.ref_name }}"
-          echo "BRANCH_NAME=$BRANCH" >> $GITHUB_OUTPUT
-        #   if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
-        #     echo "BRANCH_NAME=${{ inputs.branch }}" >> $GITHUB_ENV
-        #     echo "DEFINITION_ID=${{ inputs.definition_id }}" >> $GITHUB_ENV
-        #   else
-        #     echo "BRANCH_NAME=${{ github.ref_name }}" >> $GITHUB_ENV
-        #     echo "DEFINITION_ID=${{ secrets.CIRCLE_DEFINITION_ID }}" >> $GITHUB_ENV
-        #   fi
+#     steps:
+#       - name : Setup runtime variables
+#         id : setup
+#         run: |
+#           BRANCH="${{ inputs.branch || github.ref_name }}"
+#           echo "BRANCH_NAME=$BRANCH" >> $GITHUB_OUTPUT
+#         #   if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
+#         #     echo "BRANCH_NAME=${{ inputs.branch }}" >> $GITHUB_ENV
+#         #     echo "DEFINITION_ID=${{ inputs.definition_id }}" >> $GITHUB_ENV
+#         #   else
+#         #     echo "BRANCH_NAME=${{ github.ref_name }}" >> $GITHUB_ENV
+#         #     echo "DEFINITION_ID=${{ secrets.CIRCLE_DEFINITION_ID }}" >> $GITHUB_ENV
+#         #   fi
 
 
 
-      - name: Trigger CircleCI pipeline
-        env:
-          CIRCLE_TOKEN: ${{ secrets.CIRCLE_TOKEN }}
-          PROJECT_SLUG: ${{ secrets.CIRCLE_PROJECT_SLUG }}
-          DEFINITION_ID: ${{ secrets.CIRCLE_DEFINITION_ID }}
-          BRANCH_NAME: ${{ steps.setup.outputs.BRANCH_NAME }}
-        run: |
-          echo "Triggering CircleCI pipeline for branch: ${BRANCH_NAME}"
+#       - name: Trigger CircleCI pipeline
+#         env:
+#           CIRCLE_TOKEN: ${{ secrets.CIRCLE_TOKEN }}
+#           PROJECT_SLUG: ${{ secrets.CIRCLE_PROJECT_SLUG }}
+#           DEFINITION_ID: ${{ secrets.CIRCLE_DEFINITION_ID }}
+#           BRANCH_NAME: ${{ steps.setup.outputs.BRANCH_NAME }}
+#         run: |
+#           echo "Triggering CircleCI pipeline for branch: ${BRANCH_NAME}"
 
-          RESPONSE=$(curl -s -X POST https://circleci.com/api/v2/project/$PROJECT_SLUG/pipeline/run \
-            -H "Circle-Token: $CIRCLE_TOKEN" \
-            -H "Content-Type: application/json" \
-            -d "$(jq -n \
-              --arg def_id "$DEFINITION_ID" \
-              --arg branch "$BRANCH_NAME" \
-              '{
-                definition_id: $def_id,
-                config:   { branch: $branch },
-                checkout: { branch: $branch }
-              }'
-            )")
+#           RESPONSE=$(curl -s -X POST https://circleci.com/api/v2/project/$PROJECT_SLUG/pipeline/run \
+#             -H "Circle-Token: $CIRCLE_TOKEN" \
+#             -H "Content-Type: application/json" \
+#             -d "$(jq -n \
+#               --arg def_id "$DEFINITION_ID" \
+#               --arg branch "$BRANCH_NAME" \
+#               '{
+#                 definition_id: $def_id,
+#                 config:   { branch: $branch },
+#                 checkout: { branch: $branch }
+#               }'
+#             )")
 
-          PIPELINE_ID=$(jq -r '.id // empty' <<< "$RESPONSE")
+#           PIPELINE_ID=$(jq -r '.id // empty' <<< "$RESPONSE")
 
-          if [ -z "$PIPELINE_ID" ]; then
-            echo "::error::Failed to retrieve pipeline ID. Response: $RESPONSE"
-            exit 1
-          fi
+#           if [ -z "$PIPELINE_ID" ]; then
+#             echo "::error::Failed to retrieve pipeline ID. Response: $RESPONSE"
+#             exit 1
+#           fi
 
-          echo "Pipeline triggered. ID: $PIPELINE_ID"
+#           echo "Pipeline triggered. ID: $PIPELINE_ID"
