Status Pipeline

diff --git a/.github/workflows/circleci-trigger.yml b/.github/workflows/circleci-trigger.yml
--- a/.github/workflows/circleci-trigger.yml
+++ b/.github/workflows/circleci-trigger.yml
@@ -3,22 +3,52 @@ name: Trigger CircleCI Pipeline
 on:
   push:
     branches:
-      - main  
+      - main
 
 jobs:
   trigger-circleci:
     runs-on: ubuntu-latest
 
     steps:
-      - name: Trigger CircleCI Pipeline
+      - name: Trigger CircleCI pipeline and wait for result
         env:
           CIRCLE_TOKEN: ${{ secrets.CIRCLE_TOKEN }}
           BRANCH_NAME: ${{ github.ref_name }}
         run: |
-          curl -X POST https://circleci.com/api/v2/project/circleci/QWN8vX21fhdBu8kACa4z5w/3uQARv8g1rHVnDEy5ezCSR/pipeline/run \
-          --header "Circle-Token: $CIRCLE_TOKEN" \
-          --header "content-type: application/json" \
-          --data '{
+
+          echo "Triggering CircleCI pipeline..."
+
+          RESPONSE=$(curl -s -X POST https://circleci.com/api/v2/project/circleci/QWN8vX21fhdBu8kACa4z5w/3uQARv8g1rHVnDEy5ezCSR/pipeline/run \
+          -H "Circle-Token: $CIRCLE_TOKEN" \
+          -H "Content-Type: application/json" \
+          -d '{
             "definition_id": "494369bd-56eb-414b-9989-d202a267c12f",
             "checkout": {"branch": "'"$BRANCH_NAME"'"}
-          }'
+          }')
+
+          PIPELINE_ID=$(echo $RESPONSE | jq -r '.id')
+
+          echo "Pipeline ID: $PIPELINE_ID"
+
+          sleep 20
+
+          while true
+          do
+            STATUS=$(curl -s -H "Circle-Token: $CIRCLE_TOKEN" \
+            https://circleci.com/api/v2/pipeline/$PIPELINE_ID/workflow \
+            | jq -r '.items[0].status')
+
+            echo "CircleCI status: $STATUS"
+
+            if [[ "$STATUS" == "success" ]]; then
+              echo "CircleCI pipeline succeeded"
+              exit 0
+            fi
+
+            if [[ "$STATUS" == "failed" || "$STATUS" == "canceled" ]]; then
+              echo "CircleCI pipeline failed"
+              exit 1
+            fi
+
+            sleep 10
+          done
